# Generated by Django 4.0.2 on 2022-02-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='post_file',
            new_name='photo',
        ),
    ]
