# Generated by Django 4.0.2 on 2022-02-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_rename_post_file_postmodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='fontstyle',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
