# Generated by Django 4.0.2 on 2022-03-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_remove_postmodel_fontstyle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='photo',
            field=models.URLField(),
        ),
    ]
